# Generated by Django 4.2 on 2023-12-03 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talkingcharacter', '0002_serverstatus'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_link', models.URLField(default='https://8bf3-2a02-aa16-517b-2000-d867-6b56-c9af-30ae.ngrok-free.app/view')),
                ('status', models.CharField(choices=[('DONE', 'Erledigt'), ('PENDING', 'Ausstehend')], default='PENDING', max_length=7)),
            ],
        ),
        migrations.DeleteModel(
            name='Video',
        ),
    ]
