# Generated by Django 4.2 on 2023-12-03 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talkingcharacter', '0003_videolink_delete_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='videolink',
            name='talk_id',
            field=models.CharField(default='', max_length=30),
        ),
    ]
