# Generated by Django 4.2 on 2023-12-03 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talkingcharacter', '0004_videolink_talk_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videolink',
            name='talk_id',
        ),
        migrations.AddField(
            model_name='videolink',
            name='video_id',
            field=models.CharField(default='', max_length=60),
        ),
    ]
