# Generated by Django 4.2 on 2024-01-05 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talkingcharacter', '0005_remove_videolink_talk_id_videolink_video_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
